"""add Department

Revision ID: 673b4ed14f27
Revises: 65331d14d19d
Create Date: 2025-04-01 23:09:32.476932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673b4ed14f27'
down_revision = '65331d14d19d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
