"""rename location

Revision ID: d2a236ccc844
Revises: ffbfac1e201e
Create Date: 2025-06-17 00:47:00.601623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a236ccc844'
down_revision = 'ffbfac1e201e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('address', sa.String(), nullable=True))
    op.drop_column('departments', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('location', sa.VARCHAR(), nullable=True))
    op.drop_column('departments', 'address')
    # ### end Alembic commands ###
